// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Token      string
	IpAddress  pqtype.Inet
	UserAgent  sql.NullString
	LastSeenAt sql.NullTime
	ExpiresAt  time.Time
}

type TempToken struct {
	ID        uuid.UUID
	ExpiresAt time.Time
	UserID    uuid.NullUUID
	Value     string
	Used      sql.NullBool
}

type User struct {
	ID         uuid.UUID
	Email      string
	VerifiedAt sql.NullTime
	CreatedAt  time.Time
}
