// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
insert into sessions(id, user_id, token, ip_address, user_agent, expires_at) values($1, $2, $3, $4, $5, $6) returning id, user_id, token, ip_address, user_agent, last_seen_at, expires_at
`

type CreateSessionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	IpAddress sql.NullString
	UserAgent sql.NullString
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createTempToken = `-- name: CreateTempToken :one
insert into temp_tokens(id, expires_at, user_id, value) values($1, $2, $3, $4) returning id, expires_at, user_id, value, used
`

type CreateTempTokenParams struct {
	ID        uuid.UUID
	ExpiresAt time.Time
	UserID    uuid.NullUUID
	Value     string
}

func (q *Queries) CreateTempToken(ctx context.Context, arg CreateTempTokenParams) (TempToken, error) {
	row := q.db.QueryRowContext(ctx, createTempToken,
		arg.ID,
		arg.ExpiresAt,
		arg.UserID,
		arg.Value,
	)
	var i TempToken
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.UserID,
		&i.Value,
		&i.Used,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users(id, email) values($1, $2) returning id, email, verified_at, created_at
`

type CreateUserParams struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
select id, user_id, token, ip_address, user_agent, last_seen_at, expires_at from sessions where token = $1 and expires_at > $2
`

type GetSessionByTokenParams struct {
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, arg.Token, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTempToken = `-- name: GetTempToken :one
select id, expires_at, user_id, value, used from temp_tokens where value = $1
`

func (q *Queries) GetTempToken(ctx context.Context, value string) (TempToken, error) {
	row := q.db.QueryRowContext(ctx, getTempToken, value)
	var i TempToken
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.UserID,
		&i.Value,
		&i.Used,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, verified_at, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, verified_at, created_at from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setTempTokenUsed = `-- name: SetTempTokenUsed :one
update temp_tokens set used = true where value = $1 returning id, expires_at, user_id, value, used
`

func (q *Queries) SetTempTokenUsed(ctx context.Context, value string) (TempToken, error) {
	row := q.db.QueryRowContext(ctx, setTempTokenUsed, value)
	var i TempToken
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.UserID,
		&i.Value,
		&i.Used,
	)
	return i, err
}

const setUserVerified = `-- name: SetUserVerified :one
update users set verified_at = $2 where id = $1 returning id, email, verified_at, created_at
`

type SetUserVerifiedParams struct {
	ID         uuid.UUID
	VerifiedAt sql.NullTime
}

func (q *Queries) SetUserVerified(ctx context.Context, arg SetUserVerifiedParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserVerified, arg.ID, arg.VerifiedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}
